# 3.3 多次元配列とテンソル

## 3.3.1 テンソル計算

### ベクトル演算
tf.constantやtf.Variableの引数に配列を指定することで、ベクトルを利用することができます。

In [1]:
import tensorflow as tf

In [2]:
a = tf.constant([1, 2, 3], name='a')
b = tf.constant([4, 5, 6], name='b')
c = a + b

with tf.Session() as sess:
    print('a + b = ', sess.run(c))

a + b =  [5 7 9]


### 行列演算
行列を利用するには、ベクトルと同様に2次元の配列を指定します。

In [5]:
a = tf.constant([[1, 2], [3, 4]], name='a')
b = tf.constant([[1], [2]], name='b')
c = tf.matmul(a, b)

print('shape of a: ', a.shape)
print('shape of b: ', b.shape)
print('shape of c: ', c.shape)

with tf.Session() as sess:
    print('a = \n', sess.run(a))
    print('b = \n', sess.run(b))
    print('c = \n', sess.run(c))

shape of a:  (2, 2)
shape of b:  (2, 1)
shape of c:  (2, 1)
a = 
 [[1 2]
 [3 4]]
b = 
 [[1]
 [2]]
c = 
 [[ 5]
 [11]]


ここでは、次式の計算を実行しています。
$$
    \left(
        \begin{array}{cc}
            1 & 2 \\
            3 & 4
        \end{array}
    \right)
    \left(
        \begin{array}{c}
            1 \\
            2
        \end{array}
    \right) = 
    \left(
        \begin{array}{c}
            5 \\
            11
        \end{array}
    \right)
$$
3次元以上の配列についても、同様に計算することができます。ベクトル演算や行列演算を含め、多次元配列同士の演算をまとめてテンソル演算と呼びます。

### テンソル演算とプレースホルダー
tf.placeholderでテンソルを受け付けらえるようにするには、shape引数を指定する必要があります。

テンソルの大きさ自体が決まっていない場合は、未知の次元方向についてNoneを指定します。

In [7]:
a = tf.placeholder(shape=(None, 2), dtype=tf.int32, name='a')

with tf.Session() as sess:
    print('-- [[1, 2]]を代入 --')
    print('a = ', sess.run(a, feed_dict={a: [[1, 2]]}))
    print('\n-- [[1, 2], [3, 4]]を代入 --')
    print('a = ', sess.run(a, feed_dict={a: [[1, 2], [3, 4]]}))

-- [[1, 2]]を代入 --
a =  [[1 2]]

-- [[1, 2], [3, 4]]を代入 --
a =  [[1 2]
 [3 4]]
